ALTER TABLE products DROP COLUMN category_id;
ALTER TABLE products DROP COLUMN brand_id;
ALTER TABLE products ADD COLUMN category VARCHAR(50) NOT NULL CHECK (category IN ('BATANGAN', 'KOIN', 'PERHIASAN', 'GALERI'));
ALTER TABLE products ADD COLUMN brand VARCHAR(100) NOT NULL;
